- name: Create Jenkins Agent directory
  file:
    path: /opt/jenkins-agent
    state: directory

- name: Get Jenkins Master IP from EC2 tags
  set_fact:
    jenkins_master_ip: "{{ groups['jenkins_master'][0] }}"
  
- name: Set Jenkins Master URL
  set_fact:
    jenkins_master_url: "http://{{ jenkins_master_ip }}:8080"

- name: Download agent JAR
  get_url:
    url: "{{ jenkins_master_url }}/jnlpJars/agent.jar"
    dest: /opt/jenkins-agent/agent.jar
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Download remoting JAR
  get_url:
    url: "{{ jenkins_master_url }}/jnlpJars/remoting.jar"
    dest: /opt/jenkins-agent/remoting.jar
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Copy SSH Private Key for Jenkins Slave
  copy:
    src: ~/dev-key.pem
    dest: "{{ key_path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'